# Buildpack API version
api = "0.8"

# Buildpack ID and metadata
[buildpack]
  id = "azure-buildpacks/microsoft-openjdk"
  version = "0.0.5"

# Stacks that the buildpack will work with
[[stacks]]
id = "*"